Description: >
    Sobbosachi Mojumder / Project 2: Deploy a high-availability web app using CloudFormation

Parameters:
    InstanceType:
        Description: EC2 instance
        Type: String
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
      - Ref: InstanceSecurityGroup
      KeyName: Shovon
      ImageId: 'ami-0e1ce3e0deb8896d2' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
      InstanceType: 
      - Ref: 'InstanceType'  
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0