# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# .circleci/config.yml
defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/project

version: 2.1
commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>

jobs:
  save_hello_world_output:
    <<: *defaults
    steps:
      - run:
          command:
            cd .. && mkdir tmp && cd tmp && pwd &&
            echo "hello world" > /home/circleci/tmp/output.txt
      - persist_to_workspace:
          root: /home/circleci/tmp
          paths:
            - output.txt

  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci/tmp
      - run:
          command:
            pwd &&
            cat /home/circleci/tmp/output.txt

  print_pipeline_id:
    <<: *defaults
    steps:
      - sayhello:
          to: $CIRCLE_WORKFLOW_ID



  envir_print:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - run:
          command: 
            echo ${SOBBOSACHI}



workflows:
  welcome:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - envir_print