version: 2.1

jobs:
  cofigure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["4f:c1:9c:5b:6b:1b:74:72:d1:3c:3d:61:09:1f:20:74"]
      - run:
          name: Instal_dependencies
          command: |
            apk add --update ansible # install all the dependencies 
      - run:
          name: Configure server
          command: |
            ansible-playbook -i invertory.txt template.yml
workflows:
  my_workflow:
    jobs:
      - cofigure_infrastructure