# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
jobs:
  save_hello_world_output:
    environment:
      CODE: 123456789
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command:
            ls &&
            echo $CODE &&
            echo "hello world" > /tmp/workspace/output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output.txt

  print_output_file:
    environment:
      CODE: 567845678567845678
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command:
            ls &&
            echo $CODE &&
            cat output.txt
      - attach_workspace:
          at: /tmp/workspace

  envir_print:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: 
            echo ${SOBBOSACHI}



workflows:
  welcome:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - envir_print