# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# .circleci/config.yml
defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/project

version: 2.1
commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    parameters:
      id:
        type: string
    steps:
      - run: echo << parameters.id >>
  print_pipeline_id2:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  save_hello_world_output:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          command:
            cd .. && mkdir tmp && cd tmp && pwd &&
            docker run --rm -it amazon/aws-cli && docker run --rm -it amazon/aws-cli --version &&
            aws ec2 describe-instances  --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> /home/circleci/tmp/output.txt
      - persist_to_workspace:
          root: /home/circleci/tmp
          paths:
            - output.txt

  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci/tmp
      - run:
          command:
            pwd &&
            cat /home/circleci/tmp/output.txt

  print_pipeline_id_job:
    <<: *defaults
    steps:
      - print_pipeline_id:
          id: $CIRCLE_WORKFLOW_ID
          #id: << pipeline.id >>
  print_pipeline_id_job2:
    <<: *defaults
    steps:
      - print_pipeline_id2

  envir_print:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - run:
          command: 
            echo ${SOBBOSACHI}

  job_failures:
    <<: *defaults
    steps:
      - run: return 1
      - run:
          name: on error
          command: echo "The job has been failed. Please take care of it!!"
          when: on_fail

workflows:
  welcome:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - envir_print
      - print_pipeline_id_job
      - print_pipeline_id_job2
      - job_failures