# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    docker:
# Primary container image where all steps run.
<<<<<<< HEAD
      -image: circleci/node:13.8.0
=======
      -image: circleci/node:13.8.0
>>>>>>> 5e4f700e7b1047acefb63476a347c2cf178590c1
      steps:
      run: echo Hello!
  print_world:
    docker:
      # Primary container image where all steps run.
      -image: circleci/node:13.8.0
      steps:
      run: echo world!



workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print_hello
      - print_world
