version: 2.1

jobs:
  cofigure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["08:ae:54:ce:97:d9:49:d0:6d:6c:1a:7d:ea:50:7e"]
      - run:
          name: Instal_dependencies
          command: |
            apk add --update ansible # install all the dependencies 
      - run:
          name: Configure server
          command: |
            ansible-playbook -i invertory.txt plabook.yml
workflows:
  my_workflow:
    jobs:
      - cofigure_infrastructure