--- 
  jobs: 
    print_hello: 
      docker: 
        ? "-image"
        : "circleci/node:13.8.0"
        run: "echo Hello!"
        steps: ~
    print_world: 
      docker: 
        ? "-image"
        : "circleci/node:13.8.0"
        run: "echo world!"
        steps: ~
  orbs: 
    welcome: circleci/welcome-orb@0.4.1
  version: 2.1
  workflows: 
    welcome: 
      jobs: 
        - welcome/run
        - print_hello/run
        - print_world/run
  